### PR TITLE
Add support for the HCC format in read_mt_formats.py

### LINKED ISSUE #77: Python script to read HCC files
Extend `read_mt_formats.py` and `convert_mt_to_csv.py` scripts (both) to read HCC files containing historical data (similar as it does for other formats).

The structure of this format is explained [here](https://reverseengineering.stackexchange.com/questions/8003/need-ideas-to-reverse-engineer-this-hcc-file-format) (note: this info could be a bit out of date).

Then after running the script (`read_mt_formats.py`) I expect that all values are printed into the screen into meaningful formats, for example:

```
2015-01-02 10:00:00 1.205450 1.205450 1.205140 1.205160    31     9 22000000 
2015-01-02 10:01:00 1.205160 1.205210 1.205030 1.205030    31     6 35000000 
2015-01-02 10:02:00 1.205030 1.205030 1.204680 1.204730    51     9 54500000 
2015-01-02 10:03:00 1.204730 1.204750 1.203460 1.203850    81    18 65700000 
```

There should be two type of formats to print for `read_mt_formats.py` script, one for the header, another for data it-self.

Then the `convert_mt_to_csv.py` should print only data into CSV format, in the same format as it is for the existing HST or FXT format (the one which is most suitable for it).

For unknown fields, you can add the placeholders (e.g. unknown1, unknown2).

See also: [CSVtoHCC ](https://github.com/EA31337/CSVtoHCC) repo.

Please find the sample files in the attachment.

[EURUSD.zip](https://github.com/FX31337/FX-BT-Scripts/files/494257/EURUSD.zip)

Ref: codemill$80

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38025382-python-script-to-read-hcc-files?utm_campaign=plugin&utm_content=tracker%2F20487492&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F20487492&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LemonBoy**
Yo,
this partially solves #77 (I don't know how to use codemill though, it's the first time using it).
I didn't write the support for converting the data into the csv file because the format is quite ... complex (many headers and such) and it might make sense to deduplicate some code (the `BStruct` is quite handy for parsing).
Please let me know :)

Cheers :balloon: 

codemill-id-57e9a96678e731000348058a fixes #77

### CODE REVIEW

**Comment by kenorb** [comment]
@LemonBoy See: [FAQ](http://codemill.io/developers/faq)

> you must copy the pull request string from your CodeMill dashboard and paste it to the pull request body

**Comment by kenorb** [comment]
@LemonBoy You should also grap this task at http://codemill.io/developers/tasks/open

**Comment by LemonBoy** [comment]
I am greeted by this message when trying to grab it
```
Sorry pal. It seems that this task is not available for grabbing no more 
```

**Comment by kenorb** [comment]
@LemonBoy Can you report this issue to the [support](https://github.com/CodeMillApp/support/issues).

**Comment by kenorb** [comment]
@LemonBoy Can you re-assign again, please?

**Comment by LemonBoy** [comment]
Done, I think that everything went well this time

**Comment by kenorb** [comment]
@LemonBoy This is only for the header, are you still planing to implement the data it-self as well? Or it's included with the _hcc-header_ already? Do you need more time or the price should be increased?

**Comment by LemonBoy** [comment]
I did reverse the file format and adapted the code you provided to extract the tick data.
As of now the script dumps both the headers and the data, I didn't write the code to extract the ticks into csv form yet but if you need that too I can easily add that.

**Comment by kenorb** [comment]
@LemonBoy If it currently dumps including data, could you separate `hcc-header` from the `hcc-data` it-self? If you could extract ticks into csv form, it would be great (using `convert_mt_to_csv.py` preferably). If you complete, I'll add extra $20. Thank you.

**Comment by kenorb** [comment]
@LemonBoy Also, if you re-paste codemill-id into new comment, as the system isn't picking up this from the existing content.

**Comment by LemonBoy** [comment]
Heavy PR ahead since I had to shuffle around some code, I'm quite satisfied of the result.

codemill-id-57e9a96678e731000348058a fixes #77

**Pull request merged**
