### PR TITLE
Reduced conversion time by loading input file into memory once for 

### PR DESCRIPTION
**Pull request by Kostafun**
all timeframes. Lots of CPU cycles were wasted on converting time field in every tick in input file, separately for each timeframe.

### CODE REVIEW

**Comment by kenorb** [comment]
I'm sorry, but these commits from PR #47 started 13h ago, so I had to merge. Could you rebase your code and append relevant parts again?

**Comment by Kostafun** [comment]
Sure :) My current fix is very fast (6-7 times faster than base in my tests), but could crash on machines with not enough RAM or on a very large datasets.  I'll commit updated fix for this issue (with numpy.memmap temporary file holding input data) - it should be as fast when there are enough RAM, and with temp file in case of low RAM. I'll finish and commit it tomorrow.

**Comment by kenorb** [comment]
I had to reset the `master` to the previous state and moved the other changes into `performance` branch, as it wasn't ready yet. I'll test that out and see if I can merged it first.

**Comment by kenorb** [comment]
CI test results based on the 1 month data conversion:
Before: [Elapsed time 24 min 44 sec](https://travis-ci.org/FX31337/FX-BT-Scripts/builds/119289959)
After: [Elapsed time 12 min 56 sec](https://travis-ci.org/FX31337/FX-BT-Scripts/builds/119292244)

**Pull request merged**
