### PR TITLE
Add a nice spinning bar

### PR DESCRIPTION
**Pull request by LemonBoy**
#44 

Less is more (?)

### CODE REVIEW

**Comment by kenorb** [comment]
It's possible to make it compatible with CI output (doesn't need to show progress there, but at least it won't generate thousands of one-char lines)? Using `pv` works fine for CI.

**Comment by LemonBoy** [comment]
Travis's terminal doesn't interpret any escape sequence nor a simple `\b` so I guess the only solution is to make the bar spin at a lower rate, maybe after 10000 ticks or so

**Comment by kenorb** [comment]
Please check [test branch](https://travis-ci.org/FX31337/FX-BT-Scripts/builds/119188877), using `pv` seems to work.

Tested by: `cat /dev/urandom | pv -N 'Progress' > /dev/null`.

Travis CI:

screen shot 2016-03-29 at 10 09 03

Local (in branch `test` just run `test`):

screen shot 2016-03-29 at 10 09 55

We don't need progress in CI, just on local. It seems CI somehow detects the progress bar and it doesn't printing it.

**Comment by LemonBoy** [comment]
Better ?

**Comment by kenorb** [comment]
I think the point is to print anything, so Travis won't time out because lack of any output for longer than 10 minutes.

In branch `test` I've run:

    cat /dev/urandom | pv -N 'Progress' > /dev/null

which shows the progress locally and it seems it was showing on Travis as well, but not in real time, just after finish:

    cat /dev/urandom | pv -N 'Progress' > /dev/null
     Progress: 40.1GB 0:48:17 [14.6MB/s] [  <=>  

See: [#119190362](https://travis-ci.org/FX31337/FX-BT-Scripts/builds/119190362)

**Comment by LemonBoy** [comment]
Some text is already printed in between timeframes conversion so the problem here is to let travis know the script isn't dead during the conversion phase, the performance fixes might help here since it takes less than 10m to convert a single set, otherwise the only other option I see is to rate-limit the progressbar

**Comment by LemonBoy** [comment]
Also, see https://docs.travis-ci.com/user/common-build-problems/ about `travis_wait`

**Comment by kenorb** [comment]
Text between timeframes is not enough, since M1 is taking the longest time, probably more than 30 minutes.

**Comment by LemonBoy** [comment]
Ayy, is this ok ?

**Comment by LemonBoy** [comment]
Green :green_apple:

**Comment by kenorb** [comment]
The previous version was better, with the progress bar. I'm investigating currently if the progress bar is possible with CI.

**Comment by LemonBoy** [comment]
Nope, most projects just disable the bars alltogether when the 'CI' env variable is detected since Travis doesn't support any kind of escape sequence

**Comment by kenorb** [comment]
I did simple test in Python and it seems it works fine.

ci build

Build: [119308690](https://travis-ci.org/kenorb/travis-test/builds/119308690)
File: [`progress-bar.py`](https://github.com/kenorb/travis-test/tree/ci-progress-bar)

I think you just need to send return of the line (`\b`) and flush the stdout.

**Comment by LemonBoy** [comment]
ehh, the original version had no such luck, is a spinning bar ok ?

**Comment by kenorb** [comment]
The spinning is fine (e.g. every 1% as per issue description), but it shouldn't generate thousands of lines.
If we know the total of ticks, we can print how many ticks are of total.

**Comment by LemonBoy** [comment]
You can't know the number of ticks since the Input iterator is lazy and you'd end up reading the whole dataset twice (once for `len()` and once for the actual elaboration), so the best you could have is the crazy spinning bar :)

**Comment by kenorb** [comment]
Ok, spinning bar is fine or e.g. elapsed time.

**Comment by kenorb** [comment]
Probably because there are too many characters printed (>4MB). Can you do it each 2 seconds or every 100k or 1mln ticks?

**Comment by kenorb** [comment]
Almost.

ci build

But it's saying:

> The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

Probably too many bars in short amount of time.

**Comment by LemonBoy** [comment]
Slightly better

**Comment by kenorb** [comment]
If this can't be done in a better way, pity.

**Pull request merged**
