### PR TITLE
Performance fixes (#37, #47, #51)

### PR DESCRIPTION
**Pull request by kenorb**

### CODE REVIEW

**Comment by LemonBoy** [comment]
Cherry pick #52 too

**Comment by kenorb** [comment]
CI fail with:

	Traceback (most recent call last):
	  File "/home/travis/build/FX31337/FX-BT-Scripts/convert_csv_to_mt.py", line 426, in <module>
	    HST574(CSV(args.inputFile), outputPath, timeframe, symbol)
	  File "/home/travis/build/FX31337/FX-BT-Scripts/convert_csv_to_mt.py", line 51, in __init__
	    self._map_obj = mmap.mmap(self.path.fileno(), 0, prot=mmap.PROT_READ)
	ValueError: cannot mmap an empty file

**Comment by LemonBoy** [comment]
Let me guess, is the file `/dev/stdin` ?

**Comment by kenorb** [comment]
Nope.

    convert_csv_to_mt.py -v -i ticks.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f hst4
    ...
    [INFO] Trying to read data from ticks.csv...

**Comment by LemonBoy** [comment]
```
find . -name '*.csv' -print0 | sort -z |  -r0 cat | tee ticks.csv > /dev/null
+find . -name '*.csv' -print0
+-r0 cat
/bin/bash: -r0: command not found
+sort -z
+tee ticks.csv
```
The pipeline's gone wild heh

**Comment by kenorb** [comment]
@LemonBoy There was missing `xargs` variable. Fixed in b9b469d3eace3784efd06f4a7e07fa887b30d4df.

**Comment by LemonBoy** [comment]
Travis is still broken and you didn't rebase this

**Comment by kenorb** [comment]
I think the tests are fixed now in [119289959](https://travis-ci.org/FX31337/FX-BT-Scripts/builds/119289959).

**Comment by kenorb** [comment]
You can try now to rebase with master.

**Comment by LemonBoy** [comment]
ehh, this is your branch, feel free to rebase it yourself

**Comment by kenorb** [comment]
Master is now passing fine, ok, I'll check.

**Comment by kenorb** [comment]
Current [CI results](https://travis-ci.org/FX31337/FX-BT-Scripts/builds/119299509):
```
+python3 convert_csv_to_mt.py --help
Traceback (most recent call last):
  File "convert_csv_to_mt.py", line 68, in <module>
    class CSV(Input):
NameError: name 'Input' is not defined
make: *** [test-help] Error 1
```

**Comment by LemonBoy** [comment]
sigh, the two speed improving PR are actually incompatible, hence why I recommended to run travis for each PR in it's own branch

**Comment by kenorb** [comment]
As part of your PR, you can try to revert the incompatible code, so once CI pass the tests, I can re-test on local again.

**Comment by kenorb** [comment]
@LemonBoy Is this branch still useful, or can be lost?

**Comment by LemonBoy** [comment]
You can safely delete this

**Pull request closed without merging**
