### PR TITLE
Initial speedup

### PR DESCRIPTION
**Pull request by LemonBoy**
I do see a 2x speedup, it might (or might not) be enough for #37

### CODE REVIEW

**Comment by kenorb** [comment]
Can you rebase please?

**Comment by LemonBoy** [comment]
Done!

**Comment by LemonBoy** [comment]
The use of `mmap` brings the time for the conversion of a single timeframe from > 12m to 6.40m (the run time for a single csv drops from `0.208s` to `0.08s`) on this machine, at the expense of being able to use stdin as input (that wasn't working well anyway as seen in #25, probably due to some buffering issue linked to the use of readline).
That's a non issue since a shared map is created and it should be shared among the various processes mapping the same file, more than a single timeframe could be converted at once to get well past the `50m` mark

**Comment by LemonBoy** [comment]
The latest commit manages to convert the whole `EURUSD-2014` dataset in less than 10m

`make  484.43s user 0.27s system 99% cpu 8:04.77 total`

At this point I'm not sure if I did optimize the code or have somehow killed the dataset heh

**Comment by kenorb** [comment]
@LemonBoy I think something got broken as I've 3 minutes and the data isn't right (too small).

	test/FX-BT-Data-EURUSD-DS $ time make
	+ which gxargs xargs
	+ head -n1
	+ find EURUSD -maxdepth 0
	+ cd EURUSD
	+ find 2014 -type d -maxdepth 0
	+ du -sb EURUSD
	+ cut -f1
	convert_csv_to_mt.py -v -i all.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f hst4
	+ convert_csv_to_mt.py -v -i all.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f hst4
	[INFO] Input file: all.csv
	[INFO] Symbol name: EURUSD
	[INFO] Timeframe: M1,M5,M15,M30,H1,H4,D1,W1,MN - [1, 5, 15, 30, 60, 240, 1440, 10080, 43200] minute(s)
	[INFO] Spread: 20
	[INFO] Output directory: .
	[INFO] Server name: default
	[INFO] Output format: hst4
	[INFO] Trying to read data from all.csv...
	gzip -v *.hst
	+ gzip -v EURUSD1.hst EURUSD10080.hst EURUSD1440.hst EURUSD15.hst EURUSD240.hst EURUSD30.hst EURUSD43200.hst EURUSD5.hst EURUSD60.hst
	EURUSD1.hst:	  -99.9% -- replaced with EURUSD1.hst.gz
	EURUSD10080.hst:	  -99.9% -- replaced with EURUSD10080.hst.gz
	EURUSD1440.hst:	  -99.9% -- replaced with EURUSD1440.hst.gz
	EURUSD15.hst:	  -99.9% -- replaced with EURUSD15.hst.gz
	EURUSD240.hst:	  -99.9% -- replaced with EURUSD240.hst.gz
	EURUSD30.hst:	  -99.9% -- replaced with EURUSD30.hst.gz
	EURUSD43200.hst:	  -99.9% -- replaced with EURUSD43200.hst.gz
	EURUSD5.hst:	  -99.9% -- replaced with EURUSD5.hst.gz
	EURUSD60.hst:	  -99.9% -- replaced with EURUSD60.hst.gz
	convert_csv_to_mt.py -v -i all.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f fxt4
	+ convert_csv_to_mt.py -v -i all.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f fxt4
	[INFO] Input file: all.csv
	[INFO] Symbol name: EURUSD
	[INFO] Timeframe: M1,M5,M15,M30,H1,H4,D1,W1,MN - [1, 5, 15, 30, 60, 240, 1440, 10080, 43200] minute(s)
	[INFO] Spread: 20
	[INFO] Output directory: .
	[INFO] Server name: default
	[INFO] Output format: fxt4
	[INFO] Trying to read data from all.csv...
	gzip -v *.fxt
	+ gzip -v EURUSD10080_0.fxt EURUSD1440_0.fxt EURUSD15_0.fxt EURUSD1_0.fxt EURUSD240_0.fxt EURUSD30_0.fxt EURUSD43200_0.fxt EURUSD5_0.fxt EURUSD60_0.fxt
	EURUSD10080_0.fxt:	  -99.9% -- replaced with EURUSD10080_0.fxt.gz
	EURUSD1440_0.fxt:	  -99.9% -- replaced with EURUSD1440_0.fxt.gz
	EURUSD15_0.fxt:	  -99.9% -- replaced with EURUSD15_0.fxt.gz
	EURUSD1_0.fxt:	  -99.9% -- replaced with EURUSD1_0.fxt.gz
	EURUSD240_0.fxt:	  -99.9% -- replaced with EURUSD240_0.fxt.gz
	EURUSD30_0.fxt:	  -99.9% -- replaced with EURUSD30_0.fxt.gz
	EURUSD43200_0.fxt:	  -99.9% -- replaced with EURUSD43200_0.fxt.gz
	EURUSD5_0.fxt:	  -99.9% -- replaced with EURUSD5_0.fxt.gz
	EURUSD60_0.fxt:	  -99.9% -- replaced with EURUSD60_0.fxt.gz
	git tag
	+ git tag
	2014
	+ echo Done.
	Done.

	real	3m25.655s
	user	3m22.522s
	sys	0m1.517s
	
	test/FX-BT-Data-EURUSD-DS $ ll *.gz
	-rw-r--r-- 1 kenorb 32 Mar 29 11:16 EURUSD1.hst.gz
	-rw-r--r-- 1 kenorb 36 Mar 29 11:16 EURUSD10080.hst.gz
	-rw-r--r-- 1 kenorb 38 Mar 29 11:18 EURUSD10080_0.fxt.gz
	-rw-r--r-- 1 kenorb 35 Mar 29 11:16 EURUSD1440.hst.gz
	-rw-r--r-- 1 kenorb 37 Mar 29 11:18 EURUSD1440_0.fxt.gz
	-rw-r--r-- 1 kenorb 33 Mar 29 11:16 EURUSD15.hst.gz
	-rw-r--r-- 1 kenorb 35 Mar 29 11:18 EURUSD15_0.fxt.gz
	-rw-r--r-- 1 kenorb 34 Mar 29 11:18 EURUSD1_0.fxt.gz
	-rw-r--r-- 1 kenorb 34 Mar 29 11:16 EURUSD240.hst.gz
	-rw-r--r-- 1 kenorb 36 Mar 29 11:18 EURUSD240_0.fxt.gz
	-rw-r--r-- 1 kenorb 33 Mar 29 11:16 EURUSD30.hst.gz
	-rw-r--r-- 1 kenorb 35 Mar 29 11:18 EURUSD30_0.fxt.gz
	-rw-r--r-- 1 kenorb 36 Mar 29 11:16 EURUSD43200.hst.gz
	-rw-r--r-- 1 kenorb 38 Mar 29 11:18 EURUSD43200_0.fxt.gz
	-rw-r--r-- 1 kenorb 32 Mar 29 11:16 EURUSD5.hst.gz
	-rw-r--r-- 1 kenorb 34 Mar 29 11:18 EURUSD5_0.fxt.gz
	-rw-r--r-- 1 kenorb 33 Mar 29 11:16 EURUSD60.hst.gz
	-rw-r--r-- 1 kenorb 35 Mar 29 11:18 EURUSD60_0.fxt.gz

It looks like it's failing silently.

**Comment by LemonBoy** [comment]
Please remove the line [1], it's a brainfart

[1] https://github.com/FX31337/FX-BT-Scripts/blob/master/convert_csv_to_mt.py#L244

**Comment by kenorb** [comment]
Can you quote the line?
Currently it's pointing to:

    for tick in ticks:

**Comment by LemonBoy** [comment]
That's the line, the branch wasn't quite ready for getting merged into master :(

**Comment by kenorb** [comment]
That's fine, it was merged to re-validate with other PR aiming at the performance to avoid any conflicts, you can send the next PR for the speed up and fixes.

**Comment by kenorb** [comment]
Moved the changes to `performance` branch (#54), so you may apply the fixes there.

**Pull request merged**
