### PR TITLE
New formats

### PR DESCRIPTION
**Pull request by LemonBoy**
#41 #42 #43 :tada:

### CODE REVIEW

**Comment by kenorb** [comment]
Can you rebase please?

**Comment by LemonBoy** [comment]
Done!

**Comment by kenorb** [comment]
Could you also add:

    #!/usr/bin/env python3

so the script is executable from the shell?

**Comment by LemonBoy** [comment]
Added

**Comment by kenorb** [comment]
To merge it, you'll have to rebase and cleanup the PR to apply only for new formats, since it's introducing the performance changes which haven't been tested yet.

**Comment by LemonBoy** [comment]
Rebased hopefully for the last time

**Comment by LemonBoy** [comment]
Eh, the build error is completely unrelated to the PR

**Pull request merged**
