### PR TITLE
Fixed to Makefile and convert_mt_to_csv.py (#12 & #10)

### PR DESCRIPTION
**Pull request by kenorb**

### CODE REVIEW

**Comment by kenorb** [comment]
@d-a-t-a-d-i-t  [Test](https://travis-ci.org/FX31337/FX-BT-Scripts/builds/82583232) didn't pass, could you find some workaround?

**Comment by d-a-t-a-d-i-t** [comment]
Hmm, the LZMA bug has returned... I changed the buffer parameter again, please try with that. Interesting, that it didn't cause any problems with previous size and Python 3.4.

**Comment by kenorb** [comment]
Travis CI has Python 3.5. Each commit that you push to your fork will appear hear and will be automatically re-tested. You can see X next to your commit, it failed as well.

**Comment by d-a-t-a-d-i-t** [comment]
*OMG* :-D I don't know why they haven't fixed this bug already in liblzma!
Well, the ultimate workaround is to decrease buffer-window to 1. :-/ I tried to just catch this EOFError exception and pass but in that case the file wasn't uncompressed totally so processing stopped with another error. I'll try to decrease it until runs smoothly...

**Comment by d-a-t-a-d-i-t** [comment]
Is it possible to tell Travis which version of Python should it use?

**Comment by kenorb** [comment]
@d-a-t-a-d-i-t  Yes, change it in `.travis.yml` at the bottom.

**Comment by d-a-t-a-d-i-t** [comment]
We're facing to this bug, 3.5 is still affected: http://bugs.python.org/issue21872 :-(

**Comment by kenorb** [comment]
It's written that it's also reproducible in 3.4:

    Versions:	Python 3.5, Python 3.4, Python 2.7

**Comment by d-a-t-a-d-i-t** [comment]
Yeah, but with 3.4 and buffer size 1023 I haven't encountered any problems, though I converted more than a year data AFAIK.

**Comment by kenorb** [comment]
@d-a-t-a-d-i-t Seems it progressed further.

**Comment by d-a-t-a-d-i-t** [comment]
Yup, I'll remove the redundant lines from Makefile, then it'd finish much faster.

**Comment by d-a-t-a-d-i-t** [comment]
Coreutils is missing. :-)

**Comment by kenorb** [comment]
It failed on:

> /bin/bash: realpath: command not found

maybe `readlink -f -- convert_mt_to_csv.py` will work.

**Comment by d-a-t-a-d-i-t** [comment]
Is it an Ubuntu sandbox?

**Comment by kenorb** [comment]
@d-a-t-a-d-i-t Looks like Ubuntu. Click on `Build system information` on the build page, it'll show.

**Comment by d-a-t-a-d-i-t** [comment]
Do you have a Container-based or a Standard worker?

**Comment by kenorb** [comment]
@d-a-t-a-d-i-t I'm not sure. Usually I do `sudo apt-get install foo` in `before_install`, so we'll see if yours syntax would work. Looks nice.

**Comment by kenorb** [comment]
> find: The relative path `./node_modules/.bin' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove that entry from $PATH

Pretty weird error. See at [Ubuntu SE](http://askubuntu.com/q/621132/78223).

**Comment by d-a-t-a-d-i-t** [comment]
Then we can insert the directory names in front of input/output parameters in the Makefile. What do you think?

**Comment by d-a-t-a-d-i-t** [comment]
Or use absolute path for find...

**Comment by kenorb** [comment]
Try whatever it works for now, I can optimize it later on.

**Comment by kenorb** [comment]
I think the problem is with PATH value. Expand `env` command to see more. So the problem is, because PATH contains: `:./node_modules/.bin` entry, so nothing to do with our `find` command.

It's described in here: https://github.com/travis-ci/travis-ci/issues/2811

**Pull request merged**
