### PR TITLE
Support multiple timeframes in convert_csv_to_mt.py

### PR DESCRIPTION
**Pull request by LemonBoy**
Wrt #24

### CODE REVIEW

**Comment by kenorb** [comment]
Could you re-pull please (pull & push again), since the branch is out-of-date?

**Comment by LemonBoy** [comment]
Rebased :)

**Comment by kenorb** [comment]
Could you improve some messages, currently it's like:

    $ ./convert_csv_to_mt.py -v -i 2015-03-01--23h_ticks.csv -s EURUSD -p 20 -S default -t M1,M5,M15,M30,H1,H4,D1,W1,MN -f hst4
    [INFO] Input file: 2015-03-01--23h_ticks.csv
    [INFO] Symbol name: EURUSD
    [INFO] Timeframe: M1,M5,M15,M30,H1,H4,D1,W1,MN - [1, 5, 15, 30, 60, 240, 1440, 10080, 43200] minute(s)
    [INFO] Spread: 20
    [INFO] Output directory: .
    [INFO] Server name: default
    [INFO] Output format: hst4
    [INFO] Trying to read data from 2015-03-01--23h_ticks.csv...
    [INFO] Trying to read data from 2015-03-01--23h_ticks.csv...
    [INFO] Trying to read data from 2015-03-01--23h_ticks.csv...
    [INFO] Trying to read data from 2015-03-01--23h_ticks.csv...
    [INFO] Trying to read data from 2015-03-01--23h_ticks.csv...
    [INFO] Trying to read data from 2015-03-01--23h_ticks.csv...
    [INFO] Trying to read data from 2015-03-01--23h_ticks.csv...
    [INFO] Trying to read data from 2015-03-01--23h_ticks.csv...
    [INFO] Trying to read data from 2015-03-01--23h_ticks.csv...

which doesn't show which timeframe it's currently converting (currently it's repeating the same message that it's trying to read the data) which would be great to know which timeframe is currently converting.

**Comment by LemonBoy** [comment]
Added a simple message using the timeframe in minutes, I hope it's alright

**Pull request merged**
